import React, { useState } from 'react'
import Idea from './Idea'
import './Home.css';
import '../App.css';

function Home() {
    const [selected1, setSelected1] = useState(false);
    const [selected2, setSelected2] = useState(false);
    const [selected3, setSelected3] = useState(false);
    const [selected4, setSelected4] = useState(false);

    function handleClick1() {
        if(!selected1){
            setSelected1(true);
            setSelected2(false);
            setSelected3(false);
            setSelected4(false);
        }
    }

    function handleClick2() {
        if(!selected2){
            setSelected1(false);
            setSelected2(true);
            setSelected3(false);
            setSelected4(false);
        }
    }

    function handleClick3() {
        if(!selected3){
            setSelected1(false);
            setSelected2(false);
            setSelected3(true);
            setSelected4(false);
        }
    }

    function handleClick4() {
        if(!selected4){
            setSelected1(false);
            setSelected2(false);
            setSelected3(false);
            setSelected4(true);
        }
    }

    return (
        <div className='home'>
            <h1 className='heading'>Kaiju Kingz WL MarketPlace Ideas</h1>
            <div className='side-nav'>
                <h1 className='subheading'>
                    WL MarketPlace Type
                </h1>
                <div className='ideas-container'>
                    <div className={selected1 ? 'idea-container-selected' : 'idea-container'} onClick={handleClick1}>
                        <Idea 
                            info="Satoshi Runnerz, ChainScouts, Habibiz, NanoPass"
                        />
                    </div>
                    <div className={selected2 ? 'idea-container-selected' : 'idea-container'} onClick={handleClick2}>
                        <Idea 
                            info="Gacha (Raid Party), Raffle ticket system (Kaiju Kingz and most other projects)"
                        />
                    </div>
                    <div className={selected3 ? 'idea-container-selected' : 'idea-container'} onClick={handleClick3}>
                        <Idea 
                            info="Auction and Project: NanoPass BlackBoxes"
                        />
                    </div>
                    <div className={selected4 ? 'idea-container-selected' : 'idea-container'} onClick={handleClick4}>
                        <Idea 
                            info="Other Notables"
                        />
                    </div>
                </div>
                <div className='github'>
                    <a className='github-link' href='https://github.com/mPartyNec/kaiju-kingz-wl-marketplace' target='_blank' rel="noreferrer">GitHub Repo</a>
                </div>
            </div>
            <div className='main-div'>
                {(!selected1 && !selected2 && !selected3 && !selected4) && <h1 className='subheading'>
                    BING BONG    
                </h1>}
                {selected1 && <h1 className='subheading'>
                    WL marketplaces like these seem to have a solid foundation in terms of WL being
                    purchasable with their native token generated by their NFT. 
                    <br/>
                    <br/>
                    Pros: High amount of different project WL spots, relatively cheap entry into projects (Satoshi, ChainScouts, Habibiz etc). Offers deflationary (burn) aspect for the token.
                    <br/>
                    <br/>
                    Cons: FCFS basis - not guaranteed a WL spot for a good project if you sleep in a bit. Whales can buy up more WL since they probably generate more of the native token.
                    <br/>
                    <br/>
                    Extras: NanoPass seems to gate their WL marketplace to NanoPass holders (maybe only for PxN WL), however offer pleasant UI and seems to be off chain.
                </h1>}
                {selected2 && <h1 className='subheading'>
                    WL marketplace offered to us by Raid Party pre-release via their Gacha was a gamified experience where you input their dCFTI (token generated for completing tasks like sharing and liking on Twitter) into the Gacha and it raffled out WL spots. Most other projects such as Kaiju Kingz and PxQuest, offer raffles for their WL giveaways to holders.
                    <br/>
                    <br/>
                    Pros: Gacha offers gamified version of raffle, gives everyone who has the token a chance at WL, and respekfully and naturally gives more chances to those who have more token. Random raffles via Discord giveaways offer chance for everyone.
                    <br/>
                    <br/>
                    Cons: Random raffles can be bypassed by making multiple wallets and discords to have more than 1 entry.
                    Random raffle via Discord does not offer any deflationary mechanic for the native token.
                    <br/>
                    <br/>
                    Extras: Gacha takes a bit of time, but allows everyone (who has token) to play. This could lead to some WL spots not being taken and expiring depending on if they are in high enough demand or not. Could fix this by raffling off to whoever has played and didn't win, or via discord raffle.
                </h1>}
                {selected3 && <h1 className='subheading'>
                    Auctions of any kind for NFT WL will offer a strong way to determine if a project has high demand, and a strong way to burn a decent amount of token as the community will decide what the price is. However auctions favour those with more token, as they can play with the price of the WL easier than those with less token.
                    <br/>
                    <br/>
                    Extra: NanoPass offers 1 BlackBox every week containing either WL for a project, a NFT, or some of their WL marketplace token. A way to offer WL opportunity holders could be hand them out at random in a similar way to NanoPass BlackBoxes however that would require a large amount of WL to be viable for a collection like Kaiju Kingz in comparison to NanoPass.
                </h1>}
                {selected4 && <h1 className='subheading'>
                    Another thing to note is that we have rooftop rampage. This could be used to gain whitelist, or maybe a higher chance at whitelist. E.G. playing Rooftop rampage and earning a high enough score could bump your winning percentage up 1% per 10% you're over the score that is set by the founders/developers/moderators.
                    <br/>
                    <br/>
                    Rooftop Rampage can also be set up in a way to reward top 10 weekly scores with WL spots to choose from the currently available WL spots - giving a chance for those who don't have much token to risk and aren't on a desired timezone.
                    <br/>
                    <br/>
                    Dots Mention: Regular raffle with no cap on the amount of tickets that you're able to purchase - Would allow fairness to those who are more invested in the project.
                </h1>}
            </div>
        </div>
    )
}

export default Home